// Monochrome line-icon library for category icons. Uses lucide-react so
// category icons match the rest of the sidebar's visual language. Each
// entry has English search keywords; the stored DB value is the `key`.

import {
  ActivityIcon,
  AnchorIcon,
  ArchiveIcon,
  AtomIcon,
  AtSignIcon,
  AwardIcon,
  BarChartIcon,
  BatteryIcon,
  BeakerIcon,
  BellIcon,
  BirdIcon,
  BookIcon,
  BookOpenIcon,
  BookmarkIcon,
  BoxIcon,
  BracesIcon,
  BrainIcon,
  BriefcaseIcon,
  BrushIcon,
  BugIcon,
  Building2Icon,
  BuildingIcon,
  CalendarIcon,
  CameraIcon,
  CarIcon,
  CatIcon,
  CircleIcon,
  ClipboardIcon,
  ClockIcon,
  CloudIcon,
  CodeIcon,
  CogIcon,
  CompassIcon,
  ContainerIcon,
  CpuIcon,
  CrownIcon,
  DatabaseIcon,
  DogIcon,
  DropletIcon,
  DumbbellIcon,
  EyeIcon,
  FileTextIcon,
  FilmIcon,
  FilterIcon,
  FishIcon,
  FlagIcon,
  FlameIcon,
  FlaskConicalIcon,
  FlowerIcon,
  FolderIcon,
  FolderOpenIcon,
  Gamepad2Icon,
  GemIcon,
  GiftIcon,
  GitBranchIcon,
  GlobeIcon,
  GraduationCapIcon,
  HammerIcon,
  HashIcon,
  HeadphonesIcon,
  HeartIcon,
  HomeIcon,
  ImageIcon,
  InboxIcon,
  InfoIcon,
  KeyIcon,
  LeafIcon,
  LightbulbIcon,
  LinkIcon,
  ListIcon,
  LockIcon,
  MailIcon,
  MapIcon,
  MapPinIcon,
  MegaphoneIcon,
  MessageCircleIcon,
  MessageSquareIcon,
  MicIcon,
  MicroscopeIcon,
  MoonIcon,
  MountainIcon,
  MusicIcon,
  PackageIcon,
  PaletteIcon,
  PenIcon,
  PencilIcon,
  PenToolIcon,
  PhoneIcon,
  PieChartIcon,
  PillIcon,
  PlaneIcon,
  PlayIcon,
  PlugIcon,
  PresentationIcon,
  PuzzleIcon,
  RadioIcon,
  RocketIcon,
  RssIcon,
  ScissorsIcon,
  SearchIcon,
  SendIcon,
  ServerIcon,
  SettingsIcon,
  ShapesIcon,
  ShieldIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SmileIcon,
  SnowflakeIcon,
  SparklesIcon,
  SquareIcon,
  StarIcon,
  StethoscopeIcon,
  SunIcon,
  TagIcon,
  TargetIcon,
  TerminalIcon,
  ThumbsUpIcon,
  TicketIcon,
  TrendingUpIcon,
  TreesIcon,
  TriangleIcon,
  TrophyIcon,
  TvIcon,
  UserIcon,
  UsersIcon,
  VideoIcon,
  Wand2Icon,
  WebhookIcon,
  WrenchIcon,
  ZapIcon,
} from "lucide-react";
import type { ComponentType } from "react";

export type IconComponent = ComponentType<{ className?: string }>;

export type CategoryIconDef = {
  key: string;
  keywords: string;
  Icon: IconComponent;
};

export type CategoryIconGroup = {
  label: string;
  icons: CategoryIconDef[];
};

const i = (
  key: string,
  keywords: string,
  Icon: IconComponent,
): CategoryIconDef => ({ key, keywords, Icon });

export const CATEGORY_ICON_GROUPS: CategoryIconGroup[] = [
  {
    label: "Development",
    icons: [
      i("code", "code programming dev", CodeIcon),
      i("terminal", "terminal console shell command", TerminalIcon),
      i("braces", "braces snippet code json", BracesIcon),
      i("cpu", "cpu chip processor hardware", CpuIcon),
      i("database", "database storage sql data", DatabaseIcon),
      i("server", "server backend hosting", ServerIcon),
      i("cloud", "cloud hosting infra", CloudIcon),
      i("container", "container docker box", ContainerIcon),
      i("git-branch", "git branch version control", GitBranchIcon),
      i("webhook", "webhook api integration", WebhookIcon),
      i("bug", "bug debug issue error", BugIcon),
    ],
  },
  {
    label: "Work & docs",
    icons: [
      i("briefcase", "briefcase work job business", BriefcaseIcon),
      i("folder", "folder directory files", FolderIcon),
      i("folder-open", "folder open directory", FolderOpenIcon),
      i("file-text", "file document text note", FileTextIcon),
      i("clipboard", "clipboard list tasks", ClipboardIcon),
      i("inbox", "inbox incoming", InboxIcon),
      i("archive", "archive storage box", ArchiveIcon),
      i("list", "list items tasks", ListIcon),
      i("calendar", "calendar date schedule", CalendarIcon),
      i("clock", "clock time schedule", ClockIcon),
      i("mail", "mail email message", MailIcon),
      i("building", "building office company", BuildingIcon),
      i("building-2", "building company corporate", Building2Icon),
      i("presentation", "presentation slides meeting", PresentationIcon),
      i("target", "target goal aim objective", TargetIcon),
      i("lightbulb", "lightbulb idea", LightbulbIcon),
      i("rocket", "rocket launch startup space", RocketIcon),
      i("trending-up", "trending growth chart up", TrendingUpIcon),
      i("bar-chart", "bar chart graph stats data", BarChartIcon),
      i("pie-chart", "pie chart graph stats", PieChartIcon),
      i("book", "book read", BookIcon),
      i("book-open", "book open read learn", BookOpenIcon),
      i("graduation-cap", "graduation education school learn", GraduationCapIcon),
    ],
  },
  {
    label: "Media",
    icons: [
      i("image", "image photo picture", ImageIcon),
      i("camera", "camera photo", CameraIcon),
      i("video", "video record clip", VideoIcon),
      i("film", "film movie cinema", FilmIcon),
      i("music", "music song audio", MusicIcon),
      i("headphones", "headphones audio listen", HeadphonesIcon),
      i("mic", "mic microphone record voice", MicIcon),
      i("play", "play media", PlayIcon),
      i("tv", "tv television", TvIcon),
      i("radio", "radio broadcast", RadioIcon),
    ],
  },
  {
    label: "Communication",
    icons: [
      i("message-square", "message chat comment", MessageSquareIcon),
      i("message-circle", "message chat bubble", MessageCircleIcon),
      i("send", "send share", SendIcon),
      i("phone", "phone call", PhoneIcon),
      i("at-sign", "at sign mention email", AtSignIcon),
      i("bell", "bell notification alert", BellIcon),
      i("megaphone", "megaphone announce loud", MegaphoneIcon),
      i("rss", "rss feed news", RssIcon),
      i("link", "link url chain", LinkIcon),
    ],
  },
  {
    label: "Creative",
    icons: [
      i("palette", "palette art paint color design", PaletteIcon),
      i("brush", "brush paint art", BrushIcon),
      i("pen", "pen write", PenIcon),
      i("pencil", "pencil write edit draw", PencilIcon),
      i("pen-tool", "pen tool design vector", PenToolIcon),
      i("sparkles", "sparkles shiny magic ai", SparklesIcon),
      i("wand", "wand magic ai", Wand2Icon),
      i("scissors", "scissors cut", ScissorsIcon),
      i("shapes", "shapes design", ShapesIcon),
    ],
  },
  {
    label: "Nature",
    icons: [
      i("leaf", "leaf nature plant eco", LeafIcon),
      i("trees", "trees forest nature", TreesIcon),
      i("flower", "flower bloom nature", FlowerIcon),
      i("sun", "sun sunny day", SunIcon),
      i("moon", "moon night dark", MoonIcon),
      i("droplet", "droplet water drop", DropletIcon),
      i("flame", "flame fire hot", FlameIcon),
      i("mountain", "mountain peak nature", MountainIcon),
      i("snowflake", "snowflake snow winter cold", SnowflakeIcon),
    ],
  },
  {
    label: "Objects",
    icons: [
      i("wrench", "wrench tool fix repair", WrenchIcon),
      i("hammer", "hammer tool build", HammerIcon),
      i("settings", "settings gear config", SettingsIcon),
      i("cog", "cog gear settings", CogIcon),
      i("box", "box package", BoxIcon),
      i("package", "package box shipping", PackageIcon),
      i("key", "key access unlock", KeyIcon),
      i("lock", "lock secure private", LockIcon),
      i("shield", "shield security protection", ShieldIcon),
      i("tag", "tag label", TagIcon),
      i("bookmark", "bookmark save", BookmarkIcon),
      i("gift", "gift present", GiftIcon),
      i("shopping-cart", "shopping cart buy", ShoppingCartIcon),
      i("shopping-bag", "shopping bag buy", ShoppingBagIcon),
      i("puzzle", "puzzle piece", PuzzleIcon),
      i("ticket", "ticket event", TicketIcon),
      i("plug", "plug power electric", PlugIcon),
      i("battery", "battery power", BatteryIcon),
      i("beaker", "beaker science lab", BeakerIcon),
      i("flask", "flask science chemistry lab", FlaskConicalIcon),
      i("microscope", "microscope science research", MicroscopeIcon),
      i("atom", "atom science physics", AtomIcon),
    ],
  },
  {
    label: "Symbols",
    icons: [
      i("star", "star favorite", StarIcon),
      i("heart", "heart love favorite", HeartIcon),
      i("zap", "zap lightning fast energy", ZapIcon),
      i("globe", "globe world web internet", GlobeIcon),
      i("compass", "compass navigate direction", CompassIcon),
      i("map", "map location", MapIcon),
      i("map-pin", "map pin location place", MapPinIcon),
      i("flag", "flag mark", FlagIcon),
      i("award", "award medal achievement", AwardIcon),
      i("trophy", "trophy win prize champion", TrophyIcon),
      i("crown", "crown king royal premium", CrownIcon),
      i("gem", "gem diamond jewel premium", GemIcon),
      i("anchor", "anchor nautical", AnchorIcon),
      i("hash", "hash tag number", HashIcon),
      i("search", "search find", SearchIcon),
      i("filter", "filter sort", FilterIcon),
      i("eye", "eye view watch", EyeIcon),
      i("info", "info information", InfoIcon),
      i("thumbs-up", "thumbs up like", ThumbsUpIcon),
      i("circle", "circle shape", CircleIcon),
      i("square", "square shape", SquareIcon),
      i("triangle", "triangle shape", TriangleIcon),
    ],
  },
  {
    label: "People & life",
    icons: [
      i("user", "user person profile", UserIcon),
      i("users", "users people group team", UsersIcon),
      i("smile", "smile face happy", SmileIcon),
      i("brain", "brain mind think ai", BrainIcon),
      i("activity", "activity pulse health", ActivityIcon),
      i("stethoscope", "stethoscope doctor health medical", StethoscopeIcon),
      i("pill", "pill medicine health", PillIcon),
      i("home", "home house", HomeIcon),
      i("car", "car vehicle travel", CarIcon),
      i("plane", "plane flight travel", PlaneIcon),
      i("gamepad", "gamepad game gaming", Gamepad2Icon),
      i("dumbbell", "dumbbell gym fitness sport", DumbbellIcon),
      i("dog", "dog pet animal", DogIcon),
      i("cat", "cat pet animal", CatIcon),
      i("bird", "bird animal", BirdIcon),
      i("fish", "fish animal", FishIcon),
    ],
  },
];

const ALL_ICONS: CategoryIconDef[] = CATEGORY_ICON_GROUPS.flatMap(
  (g) => g.icons,
);

export const CATEGORY_ICON_MAP: Record<string, IconComponent> =
  Object.fromEntries(ALL_ICONS.map((d) => [d.key, d.Icon]));

export function searchCategoryIcons(query: string): CategoryIconDef[] {
  const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  if (terms.length === 0) return [];
  return ALL_ICONS.filter((def) => {
    const haystack = `${def.key} ${def.keywords}`;
    return terms.every((t) => haystack.includes(t));
  });
}
