// Emoji library for the category / icon picker. Each entry carries English
// search keywords so users can type "rocket" and find 🚀. Grouped into
// labelled sections for browsing; the picker also offers free-text search
// across every keyword.

export type EmojiEntry = {
  char: string;
  keywords: string;
};

export type EmojiGroup = {
  label: string;
  emoji: EmojiEntry[];
};

const e = (char: string, keywords: string): EmojiEntry => ({ char, keywords });

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    label: "Smileys",
    emoji: [
      e("😀", "grin happy smile face"),
      e("😃", "smile happy face joy"),
      e("😄", "smile happy laugh face"),
      e("😁", "grin beam happy face"),
      e("😆", "laugh happy lol face"),
      e("😅", "sweat laugh nervous face"),
      e("😂", "joy laugh cry tears funny"),
      e("🤣", "rofl lol laugh rolling funny"),
      e("🙂", "slight smile face"),
      e("🙃", "upside down silly face"),
      e("😉", "wink face"),
      e("😊", "blush smile happy face"),
      e("😇", "innocent angel halo face"),
      e("🥰", "love hearts adore face"),
      e("😍", "heart eyes love face"),
      e("🤩", "star struck excited face"),
      e("😘", "kiss blow love face"),
      e("😋", "yum tasty delicious face"),
      e("😛", "tongue silly face"),
      e("😜", "wink tongue silly face"),
      e("🤪", "zany goofy crazy face"),
      e("🤨", "raised eyebrow skeptical face"),
      e("🧐", "monocle inspect curious face"),
      e("🤓", "nerd geek glasses face"),
      e("😎", "cool sunglasses face"),
      e("🥳", "party celebrate face"),
      e("🤗", "hug hands face"),
      e("🤔", "thinking think hmm face"),
      e("🤭", "giggle oops hand face"),
      e("🤫", "shush quiet silence face"),
      e("😶", "no mouth blank face"),
      e("😏", "smirk smug face"),
      e("😒", "unamused annoyed face"),
      e("🙄", "eye roll annoyed face"),
      e("😬", "grimace awkward face"),
      e("😮‍💨", "exhale sigh relief face"),
      e("😴", "sleep zzz tired face"),
      e("🤤", "drool hungry face"),
      e("😪", "sleepy tired face"),
      e("😵", "dizzy knocked out face"),
      e("🤯", "mind blown shocked face"),
      e("🥴", "woozy drunk face"),
      e("🤢", "nausea sick face"),
      e("🤮", "vomit sick puke face"),
      e("🤧", "sneeze sick face"),
      e("🥵", "hot heat sweating face"),
      e("🥶", "cold freezing face"),
      e("😷", "mask sick medical face"),
      e("🤒", "thermometer sick fever face"),
      e("🤕", "bandage hurt injury face"),
      e("😈", "devil evil grin smiling"),
      e("👿", "devil angry imp evil"),
      e("👻", "ghost spooky halloween"),
      e("💀", "skull death dead"),
      e("☠️", "skull crossbones danger poison"),
      e("👽", "alien ufo extraterrestrial"),
      e("👾", "alien monster game invader"),
      e("🤖", "robot bot android machine"),
      e("🎃", "pumpkin halloween jack lantern"),
      e("😺", "cat smile happy"),
    ],
  },
  {
    label: "People & gestures",
    emoji: [
      e("👋", "wave hello hi goodbye hand"),
      e("🤚", "raised back hand"),
      e("✋", "raised hand stop high five"),
      e("🖖", "vulcan spock hand"),
      e("👌", "ok perfect hand"),
      e("🤌", "pinched fingers italian hand"),
      e("🤏", "pinch small tiny hand"),
      e("✌️", "victory peace hand"),
      e("🤞", "crossed fingers luck hand"),
      e("🤟", "love you hand"),
      e("🤘", "rock horns metal hand"),
      e("🤙", "call me shaka hand"),
      e("👈", "point left hand"),
      e("👉", "point right hand"),
      e("👆", "point up hand"),
      e("👇", "point down hand"),
      e("☝️", "point up index hand"),
      e("👍", "thumbs up like good yes"),
      e("👎", "thumbs down dislike bad no"),
      e("✊", "fist raised power hand"),
      e("👊", "fist bump punch hand"),
      e("👏", "clap applause hand"),
      e("🙌", "raised hands celebrate praise"),
      e("👐", "open hands"),
      e("🤲", "palms up hands"),
      e("🙏", "pray thanks please hands"),
      e("🤝", "handshake deal agreement"),
      e("✍️", "writing hand pen"),
      e("💪", "muscle strong flex arm"),
      e("🦾", "mechanical arm robot prosthetic"),
      e("🧠", "brain mind smart think"),
      e("👀", "eyes look watch see"),
      e("👶", "baby infant child"),
      e("🧒", "child kid"),
      e("🧑", "person adult"),
      e("👨", "man male person"),
      e("👩", "woman female person"),
      e("🧓", "older person elder"),
      e("👮", "police officer cop"),
      e("🕵️", "detective spy investigator"),
      e("💂", "guard soldier"),
      e("👷", "construction worker builder"),
      e("🤴", "prince royal crown"),
      e("👸", "princess royal crown"),
      e("🧑‍💻", "developer programmer coder tech"),
      e("🧑‍🔬", "scientist lab researcher"),
      e("🧑‍🏫", "teacher educator school"),
      e("🧑‍🍳", "chef cook kitchen"),
      e("🧑‍🚀", "astronaut space"),
      e("🦸", "superhero hero"),
      e("🦹", "supervillain villain"),
      e("🧙", "wizard mage magic"),
      e("🧚", "fairy magic"),
      e("🧛", "vampire"),
      e("🧜", "merperson mermaid"),
      e("🧝", "elf fantasy"),
      e("👤", "silhouette person user profile"),
      e("👥", "people users group"),
      e("🗣️", "speaking head talk voice"),
      e("👣", "footprints steps"),
    ],
  },
  {
    label: "Animals & nature",
    emoji: [
      e("🐶", "dog puppy pet animal"),
      e("🐱", "cat kitten pet animal"),
      e("🐭", "mouse animal"),
      e("🐹", "hamster pet animal"),
      e("🐰", "rabbit bunny animal"),
      e("🦊", "fox animal"),
      e("🐻", "bear animal"),
      e("🐼", "panda animal"),
      e("🐨", "koala animal"),
      e("🐯", "tiger animal"),
      e("🦁", "lion animal"),
      e("🐮", "cow animal"),
      e("🐷", "pig animal"),
      e("🐸", "frog animal"),
      e("🐵", "monkey animal"),
      e("🐔", "chicken hen animal"),
      e("🐧", "penguin animal"),
      e("🐦", "bird animal"),
      e("🦆", "duck animal"),
      e("🦅", "eagle bird animal"),
      e("🦉", "owl bird animal"),
      e("🦇", "bat animal"),
      e("🐺", "wolf animal"),
      e("🐗", "boar pig animal"),
      e("🐴", "horse animal"),
      e("🦄", "unicorn magic animal"),
      e("🐝", "bee honey insect bug"),
      e("🐛", "bug caterpillar insect"),
      e("🦋", "butterfly insect"),
      e("🐌", "snail slow animal"),
      e("🐞", "ladybug beetle insect bug"),
      e("🐜", "ant insect bug"),
      e("🪲", "beetle insect bug"),
      e("🕷️", "spider insect bug"),
      e("🦂", "scorpion animal"),
      e("🐢", "turtle tortoise animal"),
      e("🐍", "snake animal"),
      e("🦎", "lizard reptile animal"),
      e("🦖", "dinosaur trex rex"),
      e("🐙", "octopus sea animal"),
      e("🦑", "squid sea animal"),
      e("🦐", "shrimp sea animal"),
      e("🦀", "crab sea animal"),
      e("🐠", "fish tropical sea animal"),
      e("🐟", "fish sea animal"),
      e("🐬", "dolphin sea animal"),
      e("🐳", "whale sea animal docker"),
      e("🐋", "whale sea animal"),
      e("🦈", "shark sea animal"),
      e("🐊", "crocodile alligator animal"),
      e("🐅", "tiger big cat animal"),
      e("🐆", "leopard cheetah animal"),
      e("🦓", "zebra animal"),
      e("🦍", "gorilla ape animal"),
      e("🐘", "elephant animal"),
      e("🦏", "rhino rhinoceros animal"),
      e("🐪", "camel animal"),
      e("🦒", "giraffe animal"),
      e("🐃", "buffalo animal"),
      e("🐎", "horse racing animal"),
      e("🐖", "pig animal"),
      e("🐑", "sheep animal"),
      e("🦙", "llama alpaca animal"),
      e("🐐", "goat animal"),
      e("🦌", "deer animal"),
      e("🐕", "dog animal pet"),
      e("🐈", "cat animal pet"),
      e("🐓", "rooster chicken animal"),
      e("🦃", "turkey bird animal"),
      e("🦚", "peacock bird animal"),
      e("🦜", "parrot bird animal"),
      e("🕊️", "dove bird peace"),
      e("🐇", "rabbit bunny animal"),
      e("🦦", "otter animal"),
      e("🐁", "mouse animal"),
      e("🐿️", "chipmunk squirrel animal"),
      e("🦔", "hedgehog animal"),
      e("🌵", "cactus plant nature"),
      e("🎄", "christmas tree holiday"),
      e("🌲", "evergreen tree pine nature"),
      e("🌳", "tree nature plant"),
      e("🌴", "palm tree nature"),
      e("🌱", "seedling plant grow nature"),
      e("🌿", "herb plant leaf nature"),
      e("☘️", "shamrock clover plant luck"),
      e("🍀", "four leaf clover luck"),
      e("🍃", "leaves wind nature plant"),
      e("🍂", "fallen leaves autumn fall"),
      e("🍁", "maple leaf autumn fall"),
      e("🍄", "mushroom fungus nature"),
      e("🐚", "shell sea beach"),
      e("🪨", "rock stone"),
      e("🌾", "wheat grain harvest"),
      e("💐", "bouquet flowers"),
      e("🌷", "tulip flower"),
      e("🌹", "rose flower love"),
      e("🌺", "hibiscus flower"),
      e("🌸", "cherry blossom flower spring"),
      e("🌼", "flower daisy blossom"),
      e("🌻", "sunflower flower"),
    ],
  },
  {
    label: "Food & drink",
    emoji: [
      e("🍏", "green apple fruit food"),
      e("🍎", "apple red fruit food"),
      e("🍐", "pear fruit food"),
      e("🍊", "orange tangerine fruit food"),
      e("🍋", "lemon fruit food sour"),
      e("🍌", "banana fruit food"),
      e("🍉", "watermelon fruit food"),
      e("🍇", "grapes fruit food"),
      e("🍓", "strawberry fruit food"),
      e("🫐", "blueberries fruit food"),
      e("🍈", "melon fruit food"),
      e("🍒", "cherries fruit food"),
      e("🍑", "peach fruit food"),
      e("🥭", "mango fruit food"),
      e("🍍", "pineapple fruit food"),
      e("🥥", "coconut fruit food"),
      e("🥝", "kiwi fruit food"),
      e("🍅", "tomato vegetable food"),
      e("🍆", "eggplant aubergine vegetable food"),
      e("🥑", "avocado fruit food"),
      e("🥦", "broccoli vegetable food"),
      e("🥬", "leafy green vegetable food"),
      e("🥒", "cucumber vegetable food"),
      e("🌶️", "chili pepper hot spicy food"),
      e("🌽", "corn vegetable food"),
      e("🥕", "carrot vegetable food"),
      e("🧄", "garlic food"),
      e("🧅", "onion food"),
      e("🥔", "potato vegetable food"),
      e("🍠", "sweet potato food"),
      e("🥐", "croissant bread food"),
      e("🥯", "bagel bread food"),
      e("🍞", "bread loaf food"),
      e("🥖", "baguette bread food"),
      e("🥨", "pretzel food"),
      e("🧀", "cheese food"),
      e("🥚", "egg food"),
      e("🍳", "cooking fried egg food"),
      e("🥞", "pancakes food breakfast"),
      e("🧇", "waffle food breakfast"),
      e("🥓", "bacon food"),
      e("🥩", "steak meat food"),
      e("🍗", "chicken leg meat food"),
      e("🍖", "meat bone food"),
      e("🌭", "hot dog food"),
      e("🍔", "burger hamburger food"),
      e("🍟", "fries food"),
      e("🍕", "pizza food"),
      e("🥪", "sandwich food"),
      e("🌮", "taco mexican food"),
      e("🌯", "burrito mexican food"),
      e("🥗", "salad food healthy"),
      e("🥘", "paella pan food"),
      e("🍝", "pasta spaghetti food"),
      e("🍜", "noodles ramen food"),
      e("🍲", "stew pot food"),
      e("🍛", "curry rice food"),
      e("🍣", "sushi food"),
      e("🍱", "bento box food"),
      e("🥟", "dumpling food"),
      e("🍤", "shrimp fried food"),
      e("🍙", "rice ball food"),
      e("🍚", "rice food"),
      e("🍥", "fish cake food"),
      e("🥮", "mooncake food"),
      e("🍢", "oden skewer food"),
      e("🍡", "dango sweet food"),
      e("🍨", "ice cream dessert food"),
      e("🍦", "soft serve ice cream dessert"),
      e("🥧", "pie dessert food"),
      e("🧁", "cupcake dessert food sweet"),
      e("🍰", "cake slice dessert food"),
      e("🎂", "birthday cake dessert"),
      e("🍮", "pudding custard dessert"),
      e("🍭", "lollipop candy sweet"),
      e("🍬", "candy sweet"),
      e("🍫", "chocolate sweet food"),
      e("🍿", "popcorn snack food"),
      e("🍩", "donut doughnut dessert food"),
      e("🍪", "cookie biscuit food"),
      e("🌰", "chestnut nut food"),
      e("🥜", "peanuts nuts food"),
      e("🍯", "honey jar food sweet"),
      e("🥛", "milk glass drink"),
      e("☕", "coffee tea hot drink"),
      e("🫖", "teapot tea drink"),
      e("🍵", "tea green drink"),
      e("🧃", "juice box drink"),
      e("🥤", "soda cup drink"),
      e("🧋", "bubble tea boba drink"),
      e("🍶", "sake drink"),
      e("🍺", "beer drink"),
      e("🍻", "beers cheers drink"),
      e("🥂", "champagne cheers toast drink"),
      e("🍷", "wine glass drink"),
      e("🥃", "whiskey glass drink"),
      e("🍸", "cocktail martini drink"),
      e("🍹", "tropical drink cocktail"),
      e("🧉", "mate drink"),
      e("🍾", "champagne bottle celebrate drink"),
    ],
  },
  {
    label: "Activities",
    emoji: [
      e("⚽", "soccer football ball sport"),
      e("🏀", "basketball ball sport"),
      e("🏈", "american football ball sport"),
      e("⚾", "baseball ball sport"),
      e("🥎", "softball ball sport"),
      e("🎾", "tennis ball sport"),
      e("🏐", "volleyball ball sport"),
      e("🏉", "rugby ball sport"),
      e("🥏", "frisbee disc sport"),
      e("🎱", "pool billiards 8 ball sport"),
      e("🏓", "ping pong table tennis sport"),
      e("🏸", "badminton sport"),
      e("🏒", "ice hockey sport"),
      e("🏑", "field hockey sport"),
      e("🥍", "lacrosse sport"),
      e("🏏", "cricket sport"),
      e("🥅", "goal net sport"),
      e("⛳", "golf flag hole sport"),
      e("🪁", "kite fly"),
      e("🏹", "bow arrow archery sport"),
      e("🎣", "fishing rod sport"),
      e("🥊", "boxing glove sport fight"),
      e("🥋", "martial arts karate judo sport"),
      e("🎽", "running shirt sport"),
      e("🛹", "skateboard sport"),
      e("🛼", "roller skate sport"),
      e("⛸️", "ice skate sport"),
      e("🎿", "ski sport snow"),
      e("🏂", "snowboard sport snow"),
      e("🪂", "parachute skydiving"),
      e("🏋️", "weight lifting gym workout sport"),
      e("🤼", "wrestling sport"),
      e("🤸", "cartwheel gymnastics sport"),
      e("⛹️", "basketball player sport"),
      e("🤺", "fencing sport"),
      e("🤾", "handball sport"),
      e("🏌️", "golf player sport"),
      e("🏇", "horse racing sport"),
      e("🧘", "yoga meditation zen relax"),
      e("🏄", "surfing sport"),
      e("🏊", "swimming sport"),
      e("🚣", "rowing boat sport"),
      e("🧗", "climbing sport"),
      e("🚵", "mountain biking cycling sport"),
      e("🚴", "cycling bike sport"),
      e("🏆", "trophy award win prize champion"),
      e("🥇", "gold medal first win"),
      e("🥈", "silver medal second"),
      e("🥉", "bronze medal third"),
      e("🏅", "medal award sport"),
      e("🎖️", "military medal award"),
      e("🏵️", "rosette award flower"),
      e("🎗️", "ribbon awareness"),
      e("🎫", "ticket admission"),
      e("🎪", "circus tent"),
      e("🤹", "juggling circus"),
      e("🎭", "theater drama masks performing arts"),
      e("🎨", "art palette paint design creative"),
      e("🎬", "movie clapper film cinema"),
      e("🎤", "microphone sing karaoke music"),
      e("🎧", "headphones music audio"),
      e("🎼", "music score sheet notes"),
      e("🎹", "piano keyboard music"),
      e("🥁", "drum music"),
      e("🎷", "saxophone music"),
      e("🎺", "trumpet music"),
      e("🎸", "guitar music"),
      e("🎻", "violin music"),
      e("🎲", "dice game random luck"),
      e("♟️", "chess pawn game strategy"),
      e("🎯", "dart target bullseye goal aim"),
      e("🎳", "bowling game sport"),
      e("🎮", "game controller gaming video game"),
      e("🎰", "slot machine casino gamble"),
      e("🧩", "puzzle piece jigsaw"),
    ],
  },
  {
    label: "Travel & places",
    emoji: [
      e("🚗", "car automobile vehicle"),
      e("🚕", "taxi cab vehicle"),
      e("🚙", "suv car vehicle"),
      e("🚌", "bus vehicle"),
      e("🏎️", "race car racing vehicle"),
      e("🚓", "police car vehicle"),
      e("🚑", "ambulance vehicle medical"),
      e("🚒", "fire truck vehicle"),
      e("🚐", "minibus van vehicle"),
      e("🛻", "pickup truck vehicle"),
      e("🚚", "delivery truck vehicle"),
      e("🚛", "truck lorry vehicle"),
      e("🚜", "tractor farm vehicle"),
      e("🛴", "scooter kick vehicle"),
      e("🚲", "bicycle bike cycle"),
      e("🛵", "motor scooter vehicle"),
      e("🏍️", "motorcycle motorbike vehicle"),
      e("🚨", "siren light alarm emergency"),
      e("🚍", "bus oncoming vehicle"),
      e("🚘", "car oncoming vehicle"),
      e("🚖", "taxi oncoming vehicle"),
      e("🚡", "aerial tramway cable car"),
      e("🚠", "mountain cableway"),
      e("🚟", "suspension railway"),
      e("🚃", "railway car train"),
      e("🚋", "tram train"),
      e("🚞", "mountain railway train"),
      e("🚄", "high speed train bullet"),
      e("🚅", "bullet train fast"),
      e("🚈", "light rail train metro"),
      e("🚂", "locomotive steam train"),
      e("🚆", "train"),
      e("🚇", "metro subway underground train"),
      e("🚊", "tram train"),
      e("🚉", "station train"),
      e("✈️", "airplane plane flight travel"),
      e("🛫", "airplane departure takeoff"),
      e("🛬", "airplane arrival landing"),
      e("🛩️", "small plane aircraft"),
      e("💺", "seat chair airplane"),
      e("🛰️", "satellite space"),
      e("🚀", "rocket launch space ship startup"),
      e("🛸", "ufo flying saucer alien"),
      e("🚁", "helicopter aircraft"),
      e("⛵", "sailboat boat sea"),
      e("🚤", "speedboat boat sea"),
      e("🛥️", "motor boat sea"),
      e("🛳️", "passenger ship cruise sea"),
      e("⛴️", "ferry boat sea"),
      e("🚢", "ship cargo sea"),
      e("⚓", "anchor sea nautical"),
      e("⛽", "fuel gas station pump"),
      e("🚧", "construction barrier warning"),
      e("🚦", "traffic light signal"),
      e("🚥", "traffic light horizontal"),
      e("🗺️", "world map travel"),
      e("🗿", "moai statue stone"),
      e("🗽", "statue of liberty new york"),
      e("🗼", "tower tokyo"),
      e("🏰", "castle palace"),
      e("🏯", "japanese castle"),
      e("🏟️", "stadium arena"),
      e("🎡", "ferris wheel fair"),
      e("🎢", "roller coaster theme park"),
      e("🎠", "carousel merry go round"),
      e("⛲", "fountain water"),
      e("🏖️", "beach umbrella sand"),
      e("🏝️", "island tropical"),
      e("🏜️", "desert sand"),
      e("🌋", "volcano eruption"),
      e("⛰️", "mountain"),
      e("🏔️", "snowy mountain peak"),
      e("🗻", "mount fuji mountain"),
      e("🏕️", "camping tent"),
      e("⛺", "tent camping"),
      e("🏠", "house home building"),
      e("🏡", "house home garden"),
      e("🏘️", "houses neighborhood"),
      e("🏗️", "construction building crane"),
      e("🏭", "factory industry building"),
      e("🏢", "office building"),
      e("🏬", "department store building"),
      e("🏥", "hospital building medical"),
      e("🏦", "bank building money"),
      e("🏨", "hotel building"),
      e("🏪", "convenience store shop"),
      e("🏫", "school building education"),
      e("🏛️", "classical building museum bank"),
      e("⛪", "church building religion"),
      e("🕌", "mosque building religion"),
      e("🕍", "synagogue building religion"),
      e("🛕", "hindu temple building religion"),
      e("🌃", "night city stars"),
      e("🌆", "city dusk sunset"),
      e("🌇", "sunset city"),
      e("🌉", "bridge night"),
      e("🌁", "foggy fog city"),
      e("🏙️", "cityscape skyline buildings"),
    ],
  },
  {
    label: "Objects",
    emoji: [
      e("⌚", "watch time wrist"),
      e("📱", "phone mobile smartphone cell"),
      e("💻", "laptop computer pc"),
      e("⌨️", "keyboard typing computer"),
      e("🖥️", "desktop computer monitor"),
      e("🖨️", "printer print"),
      e("🖱️", "mouse computer click"),
      e("🕹️", "joystick game controller"),
      e("💽", "minidisc disk storage"),
      e("💾", "floppy disk save storage"),
      e("💿", "cd disk storage"),
      e("📀", "dvd disk storage"),
      e("📷", "camera photo picture"),
      e("📸", "camera flash photo"),
      e("📹", "video camera record"),
      e("🎥", "movie camera film"),
      e("📽️", "film projector movie"),
      e("📞", "phone telephone call"),
      e("☎️", "telephone phone call"),
      e("📟", "pager device"),
      e("📠", "fax machine"),
      e("📺", "tv television"),
      e("📻", "radio audio"),
      e("🎙️", "microphone studio audio"),
      e("🧭", "compass navigation direction"),
      e("⏱️", "stopwatch timer time"),
      e("⏰", "alarm clock time"),
      e("🕰️", "mantel clock time"),
      e("⌛", "hourglass time wait"),
      e("⏳", "hourglass flowing time wait"),
      e("📡", "satellite dish antenna signal"),
      e("🔋", "battery power charge"),
      e("🔌", "plug power electric"),
      e("💡", "light bulb idea"),
      e("🔦", "flashlight torch light"),
      e("🕯️", "candle light"),
      e("🧯", "fire extinguisher safety"),
      e("🛢️", "oil drum barrel"),
      e("💸", "money flying cash spend"),
      e("💵", "dollar money cash bill"),
      e("💰", "money bag cash rich"),
      e("💳", "credit card payment money"),
      e("💎", "diamond gem jewel"),
      e("⚖️", "balance scale justice law"),
      e("🪜", "ladder"),
      e("🧰", "toolbox tools kit"),
      e("🪛", "screwdriver tool"),
      e("🔧", "wrench tool fix repair settings"),
      e("🔨", "hammer tool build"),
      e("⚒️", "hammer pick tools"),
      e("🛠️", "hammer wrench tools settings"),
      e("⛏️", "pick mining tool"),
      e("🪚", "saw tool wood"),
      e("🔩", "nut bolt screw hardware"),
      e("⚙️", "gear cog settings config"),
      e("🧱", "brick wall build"),
      e("⛓️", "chains link"),
      e("🧲", "magnet attract"),
      e("🔫", "gun water pistol"),
      e("💣", "bomb explosive"),
      e("🧨", "firecracker dynamite"),
      e("🪓", "axe tool chop"),
      e("🔪", "knife blade cut"),
      e("🗡️", "dagger sword blade"),
      e("⚔️", "swords crossed battle fight"),
      e("🛡️", "shield protection defense security"),
      e("🔮", "crystal ball magic fortune"),
      e("📿", "prayer beads"),
      e("🧿", "nazar amulet evil eye"),
      e("⚗️", "alembic chemistry science"),
      e("🔭", "telescope astronomy space"),
      e("🔬", "microscope science lab"),
      e("🩹", "bandage plaster healing"),
      e("🩺", "stethoscope doctor medical"),
      e("💊", "pill medicine drug"),
      e("💉", "syringe injection vaccine"),
      e("🧬", "dna genetics biology science"),
      e("🦠", "microbe virus bacteria germ"),
      e("🧪", "test tube science lab experiment"),
      e("🌡️", "thermometer temperature"),
      e("🧹", "broom clean sweep"),
      e("🧺", "basket laundry"),
      e("🧻", "toilet paper roll"),
      e("🚿", "shower bath water"),
      e("🛁", "bathtub bath"),
      e("🧼", "soap clean wash"),
      e("🧽", "sponge clean"),
      e("🪣", "bucket pail"),
      e("🛎️", "bell service hotel"),
      e("🔑", "key unlock access"),
      e("🗝️", "old key unlock"),
      e("🚪", "door entrance exit"),
      e("🪑", "chair seat furniture"),
      e("🛋️", "couch sofa furniture"),
      e("🛏️", "bed sleep furniture"),
      e("🧸", "teddy bear toy"),
      e("🖼️", "framed picture art image photo"),
      e("🛍️", "shopping bags"),
      e("🛒", "shopping cart trolley"),
      e("🎁", "gift present box"),
      e("🎈", "balloon party"),
      e("🎀", "ribbon bow gift"),
      e("🪄", "magic wand"),
      e("🎊", "confetti ball party celebrate"),
      e("🎉", "party popper celebrate tada"),
      e("🏮", "lantern light red"),
      e("✉️", "envelope mail letter email"),
      e("📩", "envelope arrow mail send"),
      e("📨", "incoming envelope mail"),
      e("📧", "email mail message"),
      e("💌", "love letter mail"),
      e("📥", "inbox tray download"),
      e("📤", "outbox tray upload send"),
      e("📦", "package box parcel shipping"),
      e("🏷️", "label tag price"),
      e("📪", "mailbox closed"),
      e("📫", "mailbox mail"),
      e("📬", "mailbox open mail"),
      e("📮", "postbox mail"),
      e("📜", "scroll document paper"),
      e("📄", "page document file paper"),
      e("📑", "bookmark tabs document"),
      e("🧾", "receipt invoice bill"),
      e("📊", "bar chart graph data stats"),
      e("📈", "chart increase growth trend up"),
      e("📉", "chart decrease down trend"),
      e("🗒️", "notepad notes"),
      e("📆", "calendar date schedule"),
      e("📅", "calendar date day"),
      e("🗑️", "trash bin delete waste"),
      e("🗃️", "card file box archive"),
      e("🗄️", "file cabinet drawer storage database"),
      e("📋", "clipboard list copy"),
      e("📁", "folder file directory"),
      e("📂", "open folder directory"),
      e("🗂️", "card index dividers organize folders"),
      e("🗞️", "newspaper rolled news"),
      e("📰", "newspaper news"),
      e("📓", "notebook journal"),
      e("📔", "notebook decorated journal"),
      e("📒", "ledger notebook"),
      e("📕", "book closed red"),
      e("📗", "book green"),
      e("📘", "book blue"),
      e("📙", "book orange"),
      e("📚", "books library stack"),
      e("📖", "open book read"),
      e("🔖", "bookmark"),
      e("🔗", "link chain url"),
      e("📎", "paperclip attach"),
      e("🖇️", "linked paperclips attach"),
      e("📐", "triangle ruler measure"),
      e("📏", "ruler measure straight"),
      e("🧮", "abacus calculate math"),
      e("📌", "pushpin pin"),
      e("📍", "location pin map place"),
      e("✂️", "scissors cut"),
      e("🖊️", "pen write"),
      e("🖋️", "fountain pen write"),
      e("✒️", "nib pen write"),
      e("🖌️", "paintbrush paint art"),
      e("🖍️", "crayon color draw"),
      e("📝", "memo note write pencil edit"),
      e("✏️", "pencil write edit"),
      e("🔍", "magnifying glass search find zoom"),
      e("🔎", "magnifying glass search find right"),
      e("🔏", "lock pen secure"),
      e("🔐", "lock key secure"),
      e("🔒", "lock closed secure private"),
      e("🔓", "unlock open"),
      e("🛗", "elevator lift"),
      e("🪟", "window"),
      e("🪞", "mirror reflection"),
      e("🧳", "luggage suitcase travel"),
      e("🌂", "umbrella closed rain"),
      e("☂️", "umbrella open rain"),
      e("🧵", "thread sewing spool"),
      e("🧶", "yarn knitting wool"),
      e("👑", "crown king queen royal"),
    ],
  },
  {
    label: "Symbols",
    emoji: [
      e("❤️", "red heart love"),
      e("🧡", "orange heart love"),
      e("💛", "yellow heart love"),
      e("💚", "green heart love"),
      e("💙", "blue heart love"),
      e("💜", "purple heart love"),
      e("🖤", "black heart love"),
      e("🤍", "white heart love"),
      e("🤎", "brown heart love"),
      e("💔", "broken heart sad"),
      e("❣️", "heart exclamation love"),
      e("💕", "two hearts love"),
      e("💞", "revolving hearts love"),
      e("💗", "growing heart love"),
      e("💖", "sparkling heart love"),
      e("💘", "heart arrow cupid love"),
      e("💝", "heart gift love"),
      e("💟", "heart decoration love"),
      e("☮️", "peace symbol"),
      e("✝️", "cross christian religion"),
      e("☪️", "star crescent islam religion"),
      e("🕉️", "om hindu religion"),
      e("☸️", "dharma wheel buddhism"),
      e("✡️", "star of david judaism religion"),
      e("☯️", "yin yang balance"),
      e("⛎", "ophiuchus zodiac"),
      e("♈", "aries zodiac"),
      e("♉", "taurus zodiac"),
      e("♊", "gemini zodiac"),
      e("♋", "cancer zodiac"),
      e("♌", "leo zodiac"),
      e("♍", "virgo zodiac"),
      e("♎", "libra zodiac"),
      e("♏", "scorpio zodiac"),
      e("♐", "sagittarius zodiac"),
      e("♑", "capricorn zodiac"),
      e("♒", "aquarius zodiac"),
      e("♓", "pisces zodiac"),
      e("⚛️", "atom science physics"),
      e("☢️", "radioactive nuclear danger"),
      e("☣️", "biohazard danger"),
      e("✴️", "eight pointed star sparkle"),
      e("❌", "cross mark x no wrong"),
      e("⭕", "circle o correct"),
      e("🛑", "stop sign octagon"),
      e("⛔", "no entry forbidden"),
      e("📛", "name badge"),
      e("🚫", "prohibited no forbidden"),
      e("💯", "hundred 100 perfect score"),
      e("💢", "anger symbol mad"),
      e("♨️", "hot springs steam"),
      e("🔞", "no under 18 adult"),
      e("❗", "exclamation warning important"),
      e("❓", "question mark help"),
      e("❕", "white exclamation"),
      e("❔", "white question mark"),
      e("‼️", "double exclamation"),
      e("⁉️", "exclamation question"),
      e("⚠️", "warning caution alert danger"),
      e("🚸", "children crossing caution"),
      e("🔱", "trident emblem"),
      e("⚜️", "fleur de lis"),
      e("🔰", "beginner novice symbol"),
      e("♻️", "recycle environment green"),
      e("✅", "check mark done yes correct ok"),
      e("❇️", "sparkle"),
      e("✳️", "asterisk star"),
      e("❎", "cross mark button no"),
      e("🌐", "globe world web internet network"),
      e("💠", "diamond shape"),
      e("🌀", "cyclone spiral swirl"),
      e("💤", "zzz sleep tired"),
      e("🏧", "atm bank money"),
      e("♿", "wheelchair accessible"),
      e("🅿️", "parking p"),
      e("🚹", "mens restroom men"),
      e("🚺", "womens restroom women"),
      e("🚻", "restroom toilet wc"),
      e("🎦", "cinema movie"),
      e("📶", "signal bars network wifi"),
      e("🔣", "symbols input"),
      e("ℹ️", "information info"),
      e("🔤", "abc letters alphabet"),
      e("🆗", "ok button"),
      e("🆙", "up button new"),
      e("🆒", "cool button"),
      e("🆕", "new button"),
      e("🆓", "free button"),
      e("➕", "plus add"),
      e("➖", "minus subtract"),
      e("➗", "divide division"),
      e("✖️", "multiply times"),
      e("♾️", "infinity forever"),
      e("💲", "dollar sign money"),
      e("™️", "trademark"),
      e("©️", "copyright"),
      e("®️", "registered"),
      e("🔚", "end arrow"),
      e("🔙", "back arrow"),
      e("🔛", "on arrow"),
      e("🔝", "top up arrow"),
      e("🔜", "soon arrow"),
      e("✔️", "check mark done yes tick"),
      e("☑️", "checkbox checked done"),
      e("🔘", "radio button"),
      e("🔴", "red circle dot"),
      e("🟠", "orange circle dot"),
      e("🟡", "yellow circle dot"),
      e("🟢", "green circle dot"),
      e("🔵", "blue circle dot"),
      e("🟣", "purple circle dot"),
      e("⚫", "black circle dot"),
      e("⚪", "white circle dot"),
      e("🟤", "brown circle dot"),
      e("🔺", "red triangle up"),
      e("🔻", "red triangle down"),
      e("🔶", "orange diamond"),
      e("🔷", "blue diamond"),
      e("🔸", "small orange diamond"),
      e("🔹", "small blue diamond"),
      e("🔳", "white square button"),
      e("🔲", "black square button"),
      e("🟥", "red square"),
      e("🟧", "orange square"),
      e("🟨", "yellow square"),
      e("🟩", "green square"),
      e("🟦", "blue square"),
      e("🟪", "purple square"),
      e("⬛", "black square"),
      e("⬜", "white square"),
      e("🟫", "brown square"),
      e("🔔", "bell notification alert"),
      e("🔕", "bell off mute silent"),
      e("📣", "megaphone announce loud"),
      e("📢", "loudspeaker announce"),
      e("💬", "speech bubble chat message comment"),
      e("💭", "thought bubble think"),
      e("🗯️", "anger speech bubble"),
      e("♠️", "spade card suit"),
      e("♣️", "club card suit"),
      e("♥️", "heart card suit"),
      e("♦️", "diamond card suit"),
      e("⭐", "star favorite"),
      e("🌟", "glowing star sparkle"),
      e("✨", "sparkles shiny magic"),
      e("⚡", "lightning bolt electric fast power"),
      e("🔥", "fire flame hot trending"),
      e("💥", "explosion boom collision"),
      e("🌈", "rainbow colors"),
      e("☀️", "sun sunny weather bright"),
      e("⛅", "cloud sun weather"),
      e("☁️", "cloud weather cloudy"),
      e("❄️", "snowflake snow cold winter"),
      e("⛄", "snowman snow winter"),
      e("💧", "droplet water drop"),
      e("💦", "sweat water splash"),
      e("🌊", "wave ocean water sea"),
    ],
  },
];

// Flat lookup for free-text search.
const ALL_EMOJI: EmojiEntry[] = EMOJI_GROUPS.flatMap((g) => g.emoji);

export function searchEmoji(query: string): EmojiEntry[] {
  const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  if (terms.length === 0) return [];
  return ALL_EMOJI.filter((entry) => {
    const haystack = entry.keywords.toLowerCase();
    return terms.every((t) => haystack.includes(t));
  });
}
